### PR TITLE
feat: remove legacy JMX progress support

### PR DESCRIPTION
**Pull request by CodeLieutenant**

### CODE REVIEW

**Comment by fruch** [comment]
is that something that was done on the scylla-java-tools ?

**Comment by fruch** [comment]
Also a general notice, they having a bit more description into the commits
future reader that would try to understand what was going on, would have hard time understand, and wouldn't have any context

**Comment by CodeLieutenant** [comment]
This is removed from Cassandra 4.x and it was just a leftover from the Cassandra sources not needed for the c-s, unused classes and tests which are not working

**Comment by CodeLieutenant** [comment]
> Also a general notice, they having a bit more description into the commits future reader that would try to understand what was going on, would have hard time understand, and wouldn't have any context

I'll be removing most of my commits (squashing them), they are unnecessary and most of them are just garbage, to make things work before transferring the repository. I'll write the good commit message when that is done with full explanations

**Pull request merged**
